[package]
name          = "amq-protocol"
version       = "7.0.0-alpha.5" # remember to update html_root_url
edition       = "2018"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP specifications"
repository    = "https://github.com/CleverCloud/amq-protocol"
documentation = "https://docs.rs/amq-protocol"
keywords      = ["amqp","rabbitmq","protocol","nom"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"
build         = "build.rs"

[lib]
name = "amq_protocol"

[features]
codegen                   = ["codegen-internal"]
codegen-internal          = ["amq-protocol-codegen"]
verbose-errors            = ["amq-protocol-types/verbose-errors"]

[build-dependencies.amq-protocol-codegen]
version  = "=7.0.0-alpha.5"
path     = "../codegen"
optional = true

[dependencies.amq-protocol-types]
version = "=7.0.0-alpha.5"
path    = "../types"

[dependencies.amq-protocol-uri]
version = "=7.0.0-alpha.5"
path    = "../uri"

[dependencies.cookie-factory]
version  = "^0.3"
features = ["std"]

[dependencies.nom]
version  = "^6.0"
features = ["std"]

[badges]
travis-ci = { repository = "sozu-proxy/amq-protocol" }
appveyor  = { repository = "Keruspe/amq-protocol" }
